--Michael Weinberger 4AHIT, erstellt am 22.03.2015

INSERT INTO Trainer VALUES (20);
INSERT INTO Trainer VALUES (17);
INSERT INTO Trainer VALUES (5);
INSERT INTO Trainer VALUES (34);
INSERT INTO Trainer VALUES (68);
INSERT INTO Trainer VALUES (74);
INSERT INTO Trainer VALUES (87);
INSERT INTO Trainer VALUES (35);
INSERT INTO Trainer VALUES (37);
INSERT INTO Trainer VALUES (10);